In [12]:
import numpy as np 

In [18]:
arr = np.array([1,2,3,5,6,7,8])

In [20]:
print(arr)                                                                                                                                                                                                                                                                                                                                                                                                   

[1 2 3 5 6 7 8]


In [21]:
result = arr ** 2

In [22]:
print(result)

[ 1  4  9 25 36 49 64]


In [25]:
data = np.array([[ 0 ,  1 , 2],
                 [ 3 , 4 , 5],
                 [ 6 , 7 , 8],
                 [ 9 ,10 ,11],
                 [12 ,13 ,14]])

In [30]:
mean =  data.mean(axis=0)
std = data.std(axis=0)
print(mean)
print(std)

[6. 7. 8.]
[4.24264069 4.24264069 4.24264069]


In [31]:
normalized_data = (data - mean)/ std 

In [32]:
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [35]:
arr2 = data.flatten()

In [36]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [37]:
np.min(arr2)

np.int64(0)

In [38]:
np.max(arr2)

np.int64(14)

In [39]:
np.sum(arr2)

np.int64(105)

In [40]:
np.prod(arr2)

np.int64(0)

In [41]:
np.median(arr)

np.float64(5.0)

In [42]:
np.percentile(arr2, 50)

np.float64(7.0)

In [43]:
np.argmin(arr2)

np.int64(0)