In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1,2,4,5])
arr

array([1, 2, 4, 5])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.arange(1, 100 ,11)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [14]:
np.linspace(0, 50, 5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [15]:
myarr = np.array([[1,2,3], [2,4,5], [4,3,6], [3,5,8]])
myarr

array([[1, 2, 3],
       [2, 4, 5],
       [4, 3, 6],
       [3, 5, 8]])

In [20]:
print("Shape:" , myarr.shape)

Shape: (4, 3)


In [21]:
print("Size:" , myarr.size)

Size: 12


In [22]:
print("Dimentions:" , myarr.ndim)

Dimentions: 2


In [23]:
print("Data type:" , myarr.dtype)

Data type: int64


In [28]:
myarr = np.array([[1,2,3], [2,4,5], [4,3,6], [3,5,8]], dtype="int32")
myarr

array([[1, 2, 3],
       [2, 4, 5],
       [4, 3, 6],
       [3, 5, 8]], dtype=int32)

In [25]:
m = myarr.astype('float64')

In [26]:
m.dtype

dtype('float64')

In [29]:
myarr.dtype

dtype('int32')

In [30]:
myarr = np.array([[1,2,3], [2,4,5], [4,3,6], [3,5,8]])

In [31]:
myarr.shape

(4, 3)

In [32]:
reshaped = myarr.reshape((3,4))
reshaped

array([[1, 2, 3, 2],
       [4, 5, 4, 3],
       [6, 3, 5, 8]])