In [1]:
import numpy as np
arr = np.array([[1,2,3], [2,4,5], [4,3,6], [3,5,8]])
arr

array([[1, 2, 3],
       [2, 4, 5],
       [4, 3, 6],
       [3, 5, 8]])

In [3]:
flat = arr.flatten()
flat # persuing in one line

array([1, 2, 3, 2, 4, 5, 4, 3, 6, 3, 5, 8])

In [6]:
flat[0]

np.int64(1)

In [7]:
flat[3]

np.int64(2)

In [9]:
flat[4:8]

array([4, 5, 4, 3])

In [11]:
flat

array([1, 2, 3, 2, 4, 5, 4, 3, 6, 3, 5, 8])

In [12]:
b = flat[3:7].copy() # this in not a sliice becouse we using copy method to get the copy

In [13]:
b

array([2, 4, 5, 4])

In [14]:
b[0] = 121484
b

array([121484,      4,      5,      4])

In [16]:
arr2 = np.array([10, 20, 30, 40, 50, 60, 70])

In [17]:
arr2[[2,4,5]]

array([30, 50, 60])

In [18]:
arr2[arr2>32]

array([40, 50, 60, 70])