In [1]:
import numpy as np

arr = np.array([1,3,6,8,7])
result = arr ** 2 # Vecterization
print(result)

[ 1  9 36 64 49]


In [2]:
result + 10

array([11, 19, 46, 74, 59])

In [4]:
arr1 = np.array([[1,3,4,],[4,6,8]])
arr2 = np.array([3,4,5])
result = arr1 + arr2 # broadcasting of arr2 across arr1 
print(result)

[[ 4  7  9]
 [ 7 10 13]]
